DATA:
  DATASET: butterfly
  IMG_SIZE: 192
MODEL:
  TYPE: swinv2
  NAME: swinv2_large_patch4_window7_224_22kto1k_finetune_5shot
  DROP_PATH_RATE: 0.2
  SWINV2:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12

TRAIN:
  EPOCHS: 200
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.1
  BASE_LR: 1.25e-4 # 4096 batch-size
  WARMUP_LR: 1.25e-7
  MIN_LR: 1.25e-6

# TRAIN:
#   EPOCHS: 90
#   WARMUP_EPOCHS: 5
#   WEIGHT_DECAY: 1e-8
#   BASE_LR: 2e-05
#   WARMUP_LR: 2e-08
#   MIN_LR: 2e-07
  
  
  
  
