DATA:
  DATASET: inat21
  IMG_SIZE: 192
MODEL:
  TYPE: swinv2
  NAME: swinv2_base_patch4_window12_192_inat21
  DROP_PATH_RATE: 0.2
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12
TRAIN:
    EPOCHS: 90
    WARMUP_EPOCHS: 5
    WEIGHT_DECAY: 0.1
    BASE_LR: 1.25e-4
    WARMUP_LR: 1.25e-7
    MIN_LR: 1.25e-6
